### Particle Image Function
### Version: 1.0.4
### Width: 100
### Height: 100
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2.2 ^1.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2.25 ^1.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.35,0.34,0.34],scale:0.3} ^2.3 ^1.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2.35 ^1.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2.1 ^1.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.9,0.9,0.9],scale:0.3} ^2.15 ^1.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^2.2 ^1.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2.25 ^1.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2.3 ^1.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.95 ^1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2 ^1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.81,0.81,0.81],scale:0.3} ^2.05 ^1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^2.1 ^1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2.15 ^1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2.2 ^1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.85 ^1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.9 ^1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.1 0.1 0.1 0.3 ^1.95 ^1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^2 ^1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.99 0.99 0.3 ^2.05 ^1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2.1 ^1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.7 ^1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.75 ^1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.8 ^1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.85 ^1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.9 ^1 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.45 0.45 0.45 0.3 ^1.95 ^1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^2 ^1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.6 ^0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.65 ^0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.61 0.61 0.61 0.3 ^1.7 ^0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.75 ^0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.8 ^0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.01 0.01 0.01 0.3 ^1.85 ^0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.9 ^0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.95 ^0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.5 ^0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.55 ^0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.23 0.23 0.23 0.3 ^1.6 ^0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.65 ^0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.7 ^0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.75 ^0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.8 ^0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.85 ^0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.4 ^0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.45 ^0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.5 ^0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.55 ^0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.6 ^0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.65 ^0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.69 0.69 0.69 0.3 ^1.7 ^0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.75 ^0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.25 ^0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.3 ^0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.55 0.55 0.55 0.3 ^1.35 ^0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.4 ^0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.45 ^0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.5 ^0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.55 ^0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.09 0.09 0.09 0.3 ^1.6 ^0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.65 ^0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.15 ^0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.2 ^0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.01 0.01 0.01 0.3 ^1.25 ^0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.3 ^0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.35 ^0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.4 ^0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.45 ^0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.5 ^0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.55 ^0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.6 ^0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.05 ^0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.1 ^0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.15 ^0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.2 ^0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.25 ^0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.3 ^0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.35 ^0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.4 ^0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.96 0.96 0.96 0.3 ^1.45 ^0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.5 ^0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.9 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.95 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.65 0.65 0.65 0.3 ^1 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.05 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.1 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.15 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.2 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.25 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.3 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.35 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.4 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.45 ^0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.75 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.8 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.85 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.9 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.95 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.05 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.1 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.15 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.2 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.25 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.3 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.35 ^0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.65 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.7 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.08 0.08 0.08 0.3 ^0.75 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.8 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.85 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.9 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.95 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.05 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.1 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.15 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.18 0.18 0.18 0.3 ^1.2 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.25 ^0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.55 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.97 0.97 0.97 0.3 ^0.6 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.65 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.7 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.75 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.8 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.85 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.9 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.95 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.05 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1.1 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.15 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.2 ^0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.4 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.45 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.41 0.41 0.41 0.3 ^0.5 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.55 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.6 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.65 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.7 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.75 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.8 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.85 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.9 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.95 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^1 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.33 0.33 0.33 0.3 ^1.05 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.1 ^0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.4 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.45 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.5 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.55 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.6 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.65 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.7 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.75 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.8 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.85 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.9 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.95 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^1.05 ^0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.45 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.5 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.55 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.6 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.65 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.7 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.75 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.8 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.85 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.89 0.89 0.89 0.3 ^0.9 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.95 ^0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.35 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.4 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.05 0.05 0.05 0.3 ^0.45 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.5 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.55 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.6 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.65 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.7 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.75 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.8 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.85 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.9 ^0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.3 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.56 0.56 0.56 0.3 ^0.35 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.4 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.45 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.5 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.55 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.6 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.65 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.7 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.71 0.71 0.71 0.3 ^0.75 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.8 ^0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.3 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.15 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.2 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.74 0.74 0.74 0.3 ^0.25 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.3 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.35 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.4 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.45 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.5 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.55 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.6 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.65 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.7 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.75 ^0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.4 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.05 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.1 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.15 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.2 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.25 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.3 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.35 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.4 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.45 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.5 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.55 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.38 0.38 0.3 ^0.6 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.65 ^0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.05 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.05 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.1 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.15 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.2 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.25 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.3 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.35 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.4 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.45 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.5 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.55 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.6 ^0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.15 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.1 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.05 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.05 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.1 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.15 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.2 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.25 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.3 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.35 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.4 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.45 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.5 ^0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.3 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.25 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.76 0.76 0.76 0.3 ^-0.2 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.15 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.1 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.05 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.05 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.1 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.15 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.2 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.25 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.3 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.35 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.4 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.45 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.4 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.35 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.07 0.07 0.07 0.3 ^-0.3 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.25 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.2 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.15 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.1 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.05 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.24 0.24 0.24 0.3 ^0.05 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.99 0.99 0.3 ^0.1 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.15 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.2 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.25 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.3 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.76 0.76 0.76 0.3 ^0.35 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.4 ^-0.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.5 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.45 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.04 0.04 0.04 0.3 ^-0.4 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.35 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.3 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.25 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.2 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.15 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.11 0.11 0.11 0.3 ^-0.1 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.05 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.05 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.15 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.2 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.25 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.3 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.35 ^-0.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.6 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.55 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.5 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.45 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.4 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.35 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.3 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.25 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.76 0.76 0.76 0.3 ^-0.2 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.15 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.1 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.1 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.62 0.62 0.62 0.3 ^0.15 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.2 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.25 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.3 ^-0.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.75 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.7 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.91 0.91 0.91 0.3 ^-0.65 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.6 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.55 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.5 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.45 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.4 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.35 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.3 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.25 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.1 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.15 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.2 ^-0.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.85 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.8 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.75 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.7 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.65 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.6 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.55 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.5 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.45 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.4 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.35 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.05 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.1 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.15 ^-0.25 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.95 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.65 0.65 0.65 0.3 ^-0.9 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.85 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.8 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.75 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.7 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.65 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.6 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.55 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.5 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.45 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^0.05 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.1 ^-0.3 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.1 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.05 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.95 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.9 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.85 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.8 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.75 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.7 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.65 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.93 0.93 0.93 0.3 ^-0.6 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.55 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.05 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.24 0.24 0.24 0.3 ^0 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0.05 ^-0.35 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.15 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.1 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.28 0.28 0.28 0.3 ^-1.05 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.95 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.9 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.73 0.73 0.73 0.3 ^-0.85 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.8 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.75 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.9,0.9,0.9],scale:0.3} ^-0.7 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.65 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.1 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.38 0.38 0.38 0.3 ^-0.05 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^0 ^-0.4 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.15 ^-0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.1 ^-0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.95 ^-0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.31 0.31 0.31 0.3 ^-0.9 ^-0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.85 ^-0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.95 0.95 0.95 0.3 ^-0.8 ^-0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.75 ^-0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.15 ^-0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.45 0.45 0.45 0.3 ^-0.1 ^-0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.05 ^-0.45 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.05 ^-0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1 ^-0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-0.95 ^-0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.44 0.44 0.44 0.3 ^-0.9 ^-0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.85 ^-0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.8 ^-0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.1 ^-0.5 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.15 ^-0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.1 ^-0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.05 ^-0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0.5 0.5 0.3 ^-1 ^-0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.95 ^-0.55 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.25 ^-0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.2 ^-0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.15 ^-0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.35 0.35 0.35 0.3 ^-1.1 ^-0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.05 ^-0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1 ^-0.6 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.35 ^-0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.3 ^-0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.25 ^-0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.2 ^-0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.15 ^-0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.1 ^-0.65 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.4 ^-0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.35 ^-0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.3 ^-0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.25 ^-0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.2 ^-0.7 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.65 ^-0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.6 ^-0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.75 0.75 0.75 0.3 ^-1.55 ^-0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.5 ^-0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.45 ^-0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.4 ^-0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.35 ^-0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.3 ^-0.75 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.75 ^-0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.7 ^-0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.65 ^-0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.25 0.25 0.25 0.3 ^-1.6 ^-0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.55 ^-0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.5 ^-0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.45 ^-0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.4 ^-0.8 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.85 ^-0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.8 ^-0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.75 ^-0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.7 ^-0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.65 ^-0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.6 ^-0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.55 ^-0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.5 ^-0.85 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.95 ^-0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.9 ^-0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.02 0.02 0.02 0.3 ^-1.85 ^-0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.8 ^-0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.99 0.99 0.99 0.3 ^-1.75 ^-0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.7 ^-0.9 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2 ^-0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.41 0.41 0.41 0.3 ^-1.95 ^-0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.9 ^-0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.23 0.23 0.23 0.3 ^-1.85 ^-0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.8 ^-0.95 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.1 ^-1 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.95 0.95 0.95 0.3 ^-2.05 ^-1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-2 ^-1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-1.95 ^-1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.9 ^-1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.85 ^-1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-0.95 ^-1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.2 ^-1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.15 ^-1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-2.1 ^-1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-2.05 ^-1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.88 0.88 0.88 0.3 ^-2 ^-1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-1.95 ^-1.05 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.25 ^-1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.42 0.42 0.42 0.3 ^-2.2 ^-1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-2.15 ^-1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.1 ^-1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.05 ^-1.1 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.3 ^-1.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.0,0.0,0.0],scale:0.3} ^-2.25 ^-1.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.2 ^-1.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.15 ^-1.15 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.35 ^-1.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.3 ^-1.2 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[1.0,1.0,1.0],scale:0.3} ^-2.25 ^-1.2 ^0 0 0 0 0 1 force @a
